
PURPOSE__CHOICES = (
        ('','Purpose *'),
        ('sales','Sales'),
        ('support','Support'),
        ('complaint','Complaint'),
        ('press','Press'),
    )



GENDER__CHOICES = (
        ('','Gender *'),
        ('M','Male'),
        ('F','Female'),

    )


LOCATION__CHOICES = (
  ("Afghanistan", "Afghanistan"),
  ("Åland Islands","Åland Islands"),
  ("Albania", "Albania"),
  ("Algeria", "Algeria"),
  ("American Samoa", "American Samoa"),
  ("AndorrA", "AndorrA"),
  ("Angola", "Angola"),
  ("Anguilla", "Anguilla"),
  ("Antarctica","Antarctica"),
  ("Antigua and Barbuda", "Antigua and Barbuda"),
  ("Argentina", "Argentina"),
  ("Armenia", "Armenia"),
  ("Aruba", "Aruba"),
  ("Australia", "Australia"),
  ("Austria", "Austria"),
  ("Azerbaijan", "Azerbaijan"),
  ("Bahamas", "Bahamas"),
  ("Bahrain", "Bahrain"),
  ("Bangladesh", "Bangladesh"),
  ("Barbados", "Barbados"),
  ("Belarus", "Belarus"),
  ("Belgium", "Belgium"),
  ("Belize", "Belize"),
  ("Benin", "Benin"),
  ("Bermuda", "Bermuda"),
  ("Bhutan", "Bhutan"),
  ("Bolivia", "Bolivia"),
  ("Bosnia and Herzegovina", "Bosnia and Herzegovina"),
  ("Botswana", "Botswana"),
  ("Bouvet Island", "Bouvet Island"),
  ("Brazil", "Brazil"),
  ("British Indian Ocean Territory", "British Indian Ocean Territory"),
  ("Brunei Darussalam", "Brunei Darussalam"),
  ("Bulgaria", "Bulgaria"),
  ("Burkina Faso", "Burkina Faso"),
  ("Burundi", "Burundi"),
  ("Cambodia", "Cambodia"),
  ("Cameroon", "Cameroon"),
  ("Canada", "Canada"),
  ("Cape Verde", "Cape Verde"),
  ("Cayman Islands", "Cayman Islands"),
  ("Central African Republic","Central African Republic"),
  ("Chad", "Chad"),
  ("Chile", "Chile"),
  ("China", "China"),
  ("Christmas Island", "Christmas Island"),
  ("Cocos (Keeling) Islands","Cocos (Keeling) Islands"),
  ("Colombia", "Colombia"),
  ("Comoros", "Comoros"),
  ("Congo", "Congo"),
  ("Cook Islands", "Cook Islands"),
  ("Costa Rica", "Costa Rica"),
  ("Côte d'Ivoire", "Côte d'Ivoire"),
  ("Croatia", "Croatia"),
  ("Cuba", "Cuba"),
  ("Cyprus", "Cyprus"),
  ("Czech Republic", "Czech Republic"),
  ("Denmark", "Denmark"),
  ("Djibouti", "Djibouti"),
  ("Dominica", "Dominica"),
  ("Dominican Republic", "Dominican Republic"),
  ("Ecuador", "Ecuador"),
  ("Egypt", "Egypt"),
  ("El Salvador", "El Salvador"),
  ("Equatorial Guinea", "Equatorial Guinea"),
  ("Eritrea", "Eritrea"),
  ("Estonia", "Estonia"),
  ("Ethiopia", "Ethiopia"),
  ("Falkland Islands", "Falkland Islands"),
  ("Faroe Islands", "Faroe Islands"),
  ("Fiji", "Fiji"),
  ("Finland", "Finland"),
  ("France", "France"),
  ("French Guiana", "French Guiana"),
  ("French Polynesia", "French Polynesia"),
  ("French Southern Territories", "French Southern Territories"),
  ("Gabon", "Gabon"),
  ("Gambia", "Gambia"),
  ("Georgia", "Georgia"),
  ("Germany", "Germany"),
  ("Ghana", "Ghana"),
  ("Gibraltar", "Gibraltar"),
  ("Greece", "Greece"),
  ("Greenland", "Greenland"),
  ("Grenada", "Grenada"),
  ("Guadeloupe", "Guadeloupe"),
  ("Guam", "Guam"),
  ("Guatemala", "Guatemala"),
  ("Guernsey", "Guernsey"),
  ("Guinea", "Guinea"),
  ("Guinea-Bissau", "Guinea-Bissau"),
  ("Guyana", "Guyana"),
  ("Haiti", "Haiti"),
  ("Heard Island and Mcdonald Islands", "Heard Island and Mcdonald Islands"),
  ("Holy See", "Holy See"),
  ("Honduras", "Honduras"),
  ("Hong Kong", "Hong Kong"),
  ("Hungary", "Hungary"),
  ("Iceland", "Iceland"),
  ("India", "India"),
  ("Indonesia", "Indonesia"),
  ("Iran", "Iran"),
  ("Iraq", "Iraq"),
  ("Ireland", "Ireland"),
  ("Isle of Man", "Isle of Man"),
  ("Israel", "Israel"),
  ("Italy", "Italy"),
  ("Jamaica", "Jamaica"),
  ("Japan", "Japan"),
  ("Jersey", "Jersey"),
  ("Jordan", "Jordan"),
  ("Kazakhstan", "Kazakhstan"),
  ("Kenya", "Kenya"),
  ("Kiribati", "Kiribati"),
  ("North Korea", "North Korea"),
  ("South Korea", "South Korea"),
  ("Kuwait", "Kuwait"),
  ("Kyrgyzstan", "Kyrgyzstan"),
  ("Laos", "Laos"),
  ("Latvia", "Latvia"),
  ("Lebanon", "Lebanon"),
  ("Lesotho", "Lesotho"),
  ("Liberia", "Liberia"),
  ("Libyan Arab Jamahiriya", "Libyan Arab Jamahiriya"),
  ("Liechtenstein", "Liechtenstein"),
  ("Lithuania", "Lithuania"),
  ("Luxembourg", "Luxembourg"),
  ("Macao", "Macao"),
  ("Macedonia", "Macedonia"),
  ("Madagascar", "Madagascar"),
  ("Malawi", "Malawi"),
  ("Malaysia", "Malaysia"),
  ("Maldives", "Maldives"),
  ("Mali", "Mali"),
  ("Malta", "Malta"),
  ("Marshall Islands", "Marshall Islands"),
  ("Martinique", "Martinique"),
  ("Mauritania", "Mauritania"),
  ("Mauritius", "Mauritius"),
  ("Mayotte", "Mayotte"),
  ("Mexico", "Mexico"),
  ("Federated States of Micronesia", "Federated States of Micronesia"),
  ("Moldova", "Moldova"),
  ("Monaco", "Monaco"),
  ("Mongolia", "Mongolia"),
  ("Montserrat", "Montserrat"),
  ("Morocco", "Morocco"),
  ("Mozambique", "Mozambique"),
  ("Myanmar", "Myanmar"),
  ("Namibia", "Namibia"),
  ("Nauru", "Nauru"),
  ("Nepal", "Nepal"),
  ("Netherlands", "Netherlands"),
  ("Netherlands Antilles", "Netherlands Antilles"),
  ("New Caledonia", "New Caledonia"),
  ("New Zealand", "New Zealand"),
  ("Nicaragua", "Nicaragua"),
  ("Niger", "Niger"),
  ("Nigeria", "Nigeria"),
  ("Niue", "Niue"),
  ("Norfolk Island", "Norfolk Island"),
  ("Northern Mariana Islands", "Northern Mariana Islands"),
  ("Norway", "Norway"),
  ("Oman", "Oman"),
  ("Pakistan", "Pakistan"),
  ("Palau", "Palau"),
  ("Palestinian Territory", "Palestinian Territory"),
  ("Panama", "Panama"),
  ("Papua New Guinea", "Papua New Guinea"),
  ("Paraguay", "Paraguay"),
  ("Peru", "Peru"),
  ("Philippines", "Philippines"),
  ("Pitcairn", "Pitcairn"),
  ("Poland", "Poland"),
  ("Portugal", "Portugal"),
  ("Puerto Rico", "Puerto Rico"),
  ("Qatar", "Qatar"),
  ("Reunion", "Reunion"),
  ("Romania", "Romania"),
  ("Russian Federation", "Russian Federation"),
  ("RWANDA", "RWANDA"),
  ("Saint Helena", "Saint Helena"),
  ("Saint Kitts and Nevis", "Saint Kitts and Nevis"),
  ("Saint Lucia", "Saint Lucia"),
  ("Saint Pierre and Miquelon", "Saint Pierre and Miquelon"),
  ("Saint Vincent and the Grenadines", "Saint Vincent and the Grenadines"),
  ("Samoa", "Samoa"),
  ("San Marino", "San Marino"),
  ("Sao Tome and Principe", "Sao Tome and Principe"),
  ("Saudi Arabia", "Saudi Arabia"),
  ("Senegal", "Senegal"),
  ("Serbia and Montenegro", "Serbia and Montenegro"),
  ("Seychelles", "Seychelles"),
  ("Sierra Leone", "Sierra Leone"),
  ("Singapore", "Singapore"),
  ("Slovakia", "Slovakia"),
  ("Slovenia", "Slovenia"),
  ("Solomon Islands", "Solomon Islands"),
  ("Somalia", "Somalia"),
  ("South Africa", "South Africa"),
  ("South Georgia and the South Sandwich Islands", "South Georgia and the South Sandwich Islands"),
  ("Spain", "Spain"),
  ("Sri Lanka", "Sri Lanka"),
  ("Sudan", "Sudan"),
  ("Suri", "Suri"),
  ("Svalbard and Jan Mayen", "Svalbard and Jan Mayen"),
  ("Swaziland", "Swaziland"),
  ("Sweden", "Sweden"),
  ("Switzerland", "Switzerland"),
  ("Syrian Arab Republic", "Syrian Arab Republic"),
  ("Taiwan", "Taiwan"),
  ("Tajikistan", "Tajikistan"),
  ("Tanzania", "Tanzania"),
  ("Thailand", "Thailand"),
  ("Timor-Leste", "Timor-Leste"),
  ("Togo", "Togo"),
  ("Tokelau", "Tokelau"),
  ("Tonga", "Tonga"),
  ("Trinidad and Tobago", "Trinidad and Tobago"),
  ("Tunisia", "Tunisia"),
  ("Turkey", "Turkey"),
  ("Turkmenistan", "Turkmenistan"),
  ("Turks and Caicos Islands", "Turks and Caicos Islands"),
  ("Tuvalu", "Tuvalu"),
  ("Uganda", "Uganda"),
  ("Ukraine", "Ukraine"),
  ("United Arab Emirates", "United Arab Emirates"),
  ("United Kingdom", "United Kingdom"),
  ("United States", "United States"),
  ("United States Minor Outlying Islands", "United States Minor Outlying Islands"),
  ("Uruguay", "Uruguay"),
  ("Uzbekistan", "Uzbekistan"),
  ("Vanuatu", "Vanuatu"),
  ("Venezuela", "Venezuela"),
  ("Viet Nam", "Viet Nam"),
  ("Virgin Islands, British", "Virgin Islands, British"),
  ("Virgin Islands, U.S.", "Virgin Islands, U.S."),
  ("Wallis and Futuna", "Wallis and Futuna"),
  ("Western Sahara", "Western Sahara"),
  ("Yemen", "Yemen"),
  ("Zambia", "Zambia"),
  ("Zimbabwe", "Zimbabwe")
  # ("AF", "Afghanistan"),
  # ("AX", "Åland Islands"),
  # ("AL", "Albania"),
  # ("DZ", "Algeria"),
  # ("AS", "American Samoa"),
  # ("AD", "AndorrA"),
  # ("AO", "Angola"),
  # ("AI", "Anguilla"),
  # ("AQ", "Antarctica"),
  # ("AG", "Antigua and Barbuda"),
  # ("AR", "Argentina"),
  # ("AM", "Armenia"),
  # ("AW", "Aruba"),
  # ("AU", "Australia"),
  # ("AT", "Austria"),
  # ("AZ", "Azerbaijan"),
  # ("BS", "Bahamas"),
  # ("BH", "Bahrain"),
  # ("BD", "Bangladesh"),
  # ("BB", "Barbados"),
  # ("BY", "Belarus"),
  # ("BE", "Belgium"),
  # ("BZ", "Belize"),
  # ("BJ", "Benin"),
  # ("BM", "Bermuda"),
  # ("BT", "Bhutan"),
  # ("BO", "Bolivia"),
  # ("BA", "Bosnia and Herzegovina"),
  # ("BW", "Botswana"),
  # ("BV", "Bouvet Island"),
  # ("BR", "Brazil"),
  # ("IO", "British Indian Ocean Territory"),
  # ("BN", "Brunei Darussalam"),
  # ("BG", "Bulgaria"),
  # ("BF", "Burkina Faso"),
  # ("BI", "Burundi"),
  # ("KH", "Cambodia"),
  # ("CM", "Cameroon"),
  # ("CA", "Canada"),
  # ("CV", "Cape Verde"),
  # ("KY", "Cayman Islands"),
  # ("CF", "Central African Republic"),
  # ("TD", "Chad"),
  # ("CL", "Chile"),
  # ("CN", "China"),
  # ("CX", "Christmas Island"),
  # ("CC", "Cocos (Keeling) Islands"),
  # ("CO", "Colombia"),
  # ("KM", "Comoros"),
  # ("CG", "Congo"),
  # ("CD", "Congo"),
  # ("CK", "Cook Islands"),
  # ("CR", "Costa Rica"),
  # ("CI", "Côte d'Ivoire"),
  # ("HR", "Croatia"),
  # ("CU", "Cuba"),
  # ("CY", "Cyprus"),
  # ("CZ", "Czech Republic"),
  # ("DK", "Denmark"),
  # ("DJ", "Djibouti"),
  # ("DM", "Dominica"),
  # ("DO", "Dominican Republic"),
  # ("EC", "Ecuador"),
  # ("EG", "Egypt"),
  # ("SV", "El Salvador"),
  # ("GQ", "Equatorial Guinea"),
  # ("ER", "Eritrea"),
  # ("EE", "Estonia"),
  # ("ET", "Ethiopia"),
  # ("FK", "Falkland Islands "),
  # ("FO", "Faroe Islands"),
  # ("FJ", "Fiji"),
  # ("FI", "Finland"),
  # ("FR", "France"),
  # ("GF", "French Guiana"),
  # ("PF", "French Polynesia"),
  # ("TF", "French Southern Territories"),
  # ("GA", "Gabon"),
  # ("GM", "Gambia"),
  # ("GE", "Georgia"),
  # ("DE", "Germany"),
  # ("GH", "Ghana"),
  # ("GI", "Gibraltar"),
  # ("GR", "Greece"),
  # ("GL", "Greenland"),
  # ("GD", "Grenada"),
  # ("GP", "Guadeloupe"),
  # ("GU", "Guam"),
  # ("GT", "Guatemala"),
  # ("GG", "Guernsey"),
  # ("GN", "Guinea"),
  # ("GW", "Guinea-Bissau"),
  # ("GY", "Guyana"),
  # ("HT", "Haiti"),
  # ("HM", "Heard Island and Mcdonald Islands"),
  # ("VA", "Holy See"),
  # ("HN", "Honduras"),
  # ("HK", "Hong Kong"),
  # ("HU", "Hungary"),
  # ("IS", "Iceland"),
  # ("IN", "India"),
  # ("ID", "Indonesia"),
  # ("IR", "Iran"),
  # ("IQ", "Iraq"),
  # ("IE", "Ireland"),
  # ("IM", "Isle of Man"),
  # ("IL", "Israel"),
  # ("IT", "Italy"),
  # ("JM", "Jamaica"),
  # ("JP", "Japan"),
  # ("JE", "Jersey"),
  # ("JO", "Jordan"),
  # ("KZ", "Kazakhstan"),
  # ("KE", "Kenya"),
  # ("KI", "Kiribati"),
  # ("KP", "North Korea"),
  # ("KR", "South Korea"),
  # ("KW", "Kuwait"),
  # ("KG", "Kyrgyzstan"),
  # ("LA", "Laos"),
  # ("LV", "Latvia"),
  # ("LB", "Lebanon"),
  # ("LS", "Lesotho"),
  # ("LR", "Liberia"),
  # ("LY", "Libyan Arab Jamahiriya"),
  # ("LI", "Liechtenstein"),
  # ("LT", "Lithuania"),
  # ("LU", "Luxembourg"),
  # ("MO", "Macao"),
  # ("MK", "Macedonia"),
  # ("MG", "Madagascar"),
  # ("MW", "Malawi"),
  # ("MY", "Malaysia"),
  # ("MV", "Maldives"),
  # ("ML", "Mali"),
  # ("MT", "Malta"),
  # ("MH", "Marshall Islands"),
  # ("MQ", "Martinique"),
  # ("MR", "Mauritania"),
  # ("MU", "Mauritius"),
  # ("YT", "Mayotte"),
  # ("MX", "Mexico"),
  # ("FM", "Federated States of Micronesia"),
  # ("MD", "Moldova"),
  # ("MC", "Monaco"),
  # ("MN", "Mongolia"),
  # ("MS", "Montserrat"),
  # ("MA", "Morocco"),
  # ("MZ", "Mozambique"),
  # ("MM", "Myanmar"),
  # ("NA", "Namibia"),
  # ("NR", "Nauru"),
  # ("NP", "Nepal"),
  # ("NL", "Netherlands"),
  # ("AN", "Netherlands Antilles"),
  # ("NC", "New Caledonia"),
  # ("NZ", "New Zealand"),
  # ("NI", "Nicaragua"),
  # ("NE", "Niger"),
  # ("NG", "Nigeria"),
  # ("NU", "Niue"),
  # ("NF", "Norfolk Island"),
  # ("MP", "Northern Mariana Islands"),
  # ("NO", "Norway"),
  # ("OM", "Oman"),
  # ("PK", "Pakistan"),
  # ("PW", "Palau"),
  # ("PS", "Palestinian Territory"),
  # ("PA", "Panama"),
  # ("PG", "Papua New Guinea"),
  # ("PY", "Paraguay"),
  # ("PE", "Peru"),
  # ("PH", "Philippines"),
  # ("PN", "Pitcairn"),
  # ("PL", "Poland"),
  # ("PT", "Portugal"),
  # ("PR", "Puerto Rico"),
  # ("QA", "Qatar"),
  # ("RE", "Reunion"),
  # ("RO", "Romania"),
  # ("RU", "Russian Federation"),
  # ("RW", "RWANDA"),
  # ("SH", "Saint Helena"),
  # ("KN", "Saint Kitts and Nevis"),
  # ("LC", "Saint Lucia"),
  # ("PM", "Saint Pierre and Miquelon"),
  # ("VC", "Saint Vincent and the Grenadines"),
  # ("WS", "Samoa"),
  # ("SM", "San Marino"),
  # ("ST", "Sao Tome and Principe"),
  # ("SA", "Saudi Arabia"),
  # ("SN", "Senegal"),
  # ("CS", "Serbia and Montenegro"),
  # ("SC", "Seychelles"),
  # ("SL", "Sierra Leone"),
  # ("SG", "Singapore"),
  # ("SK", "Slovakia"),
  # ("SI", "Slovenia"),
  # ("SB", "Solomon Islands"),
  # ("SO", "Somalia"),
  # ("ZA", "South Africa"),
  # ("GS", "South Georgia and the South Sandwich Islands"),
  # ("ES", "Spain"),
  # ("LK", "Sri Lanka"),
  # ("SD", "Sudan"),
  # ("SR", "Suri"),
  # ("SJ", "Svalbard and Jan Mayen"),
  # ("SZ", "Swaziland"),
  # ("SE", "Sweden"),
  # ("CH", "Switzerland"),
  # ("SY", "Syrian Arab Republic"),
  # ("TW", "Taiwan"),
  # ("TJ", "Tajikistan"),
  # ("TZ", "Tanzania"),
  # ("TH", "Thailand"),
  # ("TL", "Timor-Leste"),
  # ("TG", "Togo"),
  # ("TK", "Tokelau"),
  # ("TO", "Tonga"),
  # ("TT", "Trinidad and Tobago"),
  # ("TN", "Tunisia"),
  # ("TR", "Turkey"),
  # ("TM", "Turkmenistan"),
  # ("TC", "Turks and Caicos Islands"),
  # ("TV", "Tuvalu"),
  # ("UG", "Uganda"),
  # ("UA", "Ukraine"),
  # ("AE", "United Arab Emirates"),
  # ("GB", "United Kingdom"),
  # ("US", "United States"),
  # ("UM", "United States Minor Outlying Islands"),
  # ("UY", "Uruguay"),
  # ("UZ", "Uzbekistan"),
  # ("VU", "Vanuatu"),
  # ("VE", "Venezuela"),
  # ("VN", "Viet Nam"),
  # ("VG", "Virgin Islands, British"),
  # ("VI", "Virgin Islands, U.S."),
  # ("WF", "Wallis and Futuna"),
  # ("EH", "Western Sahara"),
  # ("YE", "Yemen"),
  # ("ZM", "Zambia"),
  # ("Z", "Zimbabwe")
)


'''
LOCATION__CHOICES = (
        ('','Location *'),
        ('agt', 'Agartala'),
        ('agr', 'Agra'),
        ('ahmdbd', 'Ahmedabad'),
        ('ahmdngr', 'Ahmednagar'),
        ('azwl', 'Aizawl'),
        ('ajm', 'Ajmer'),
        ('akla', 'Akola'),
        ('algh', 'Aligarh'),
        ('alhbd', 'Allahabad'),
        ('alwr', 'Alwar'),
        ('amarvt', 'Amaravati'),
        ('abtr', 'Ambattur'),
        ('ambnt', 'Ambernath'),
        ('amrvt', 'Amravati'),
        ('amrtsr', 'Amritsar'),
        ('antpr', 'Anantapur'),
        ('arh', 'Arrah'),
        ('asnsl', 'Asansol'),
        ('aurgbd', 'Aurangabad'),
        ('avd', 'Avadi'),
        ('bal', 'Bally'),
        ('bnglr', 'Bangalore'),
        ('brst', 'Barasat'),
        ('barly', 'Bareilly'),
        ('btnda', 'Bathinda'),
        ('bgsr', 'Begusarai'),
        ('bel', 'Belgaum'),
        ('belr', 'Bellary'),
        ('brhmpr', 'Berhampur'),
        ('bglpr', 'Bhagalpur'),
        ('brtpr', 'Bharatpur'),
        ('batpr', 'Bhatpara'),
        ('bvngr', 'Bhavnagar'),
        ('bhli', 'Bhilai'),
        ('bhlwr', 'Bhilwara'),
        ('bwndi', 'Bhiwandi'),
        ('bpl', 'Bhopal'),
        ('bbnswar', 'Bhubaneswar'),
        ('bhrhrf ', 'Bihar Sharif'),
        ('bij', 'Bijapur'),
        ('bik', 'Bikaner'),
        ('blspr', 'Bilaspur'),
        ('bkro', 'Bokaro'),
        ('chndgr', 'Chandigarh'),
        ('chndpr', 'Chandrapur'),
        ('chn', 'Chennai'),
        ('cmbtr', 'Coimbatore'),
        ('ctk', 'Cuttack'),
        ('drbhng', 'Darbhanga'),
        ('dvngr', 'Davanagere'),
        ('drdn', 'Dehradun'),
        ('del', 'Delhi'),
        ('dew', 'Dewas'),
        ('dhnbd', 'Dhanbad'),
        ('dhu', 'Dhule'),
        ('dibrgh', 'Dibrugarh'),
        ('dur', 'Durg'),
        ('durgpr', 'Durgapur'),
        ('elr', 'Eluru'),
        ('erd', 'Erode'),
        ('etwh', 'Etawah'),
        ('faridbd', 'Faridabad'),
        ('farukbd', 'Farrukhabad'),
        ('firozbd', 'Firozabad'),
        ('gandhi', 'Gandhidham'),
        ('gandhingr', 'Gandhinagar'),
        ('gar', 'Garhwal'),
        ('gya', 'Gaya'),
        ('ghzbd', 'Ghaziabad'),
        ('ga', 'Goa'),
        ('gplpr', 'Gopalpur'),
        ('gkhpr', 'Gorakhpur'),
        ('gul', 'Gulbarga'),
        ('gtr', 'Guntur'),
        ('grgn', 'Gurgaon'),
        ('gwht', 'Guwahati'),
        ('gwalr', 'Gwalior'),
        ('hpr', 'Hapur'),
        ('hrdwr', 'Haridwar'),
        ('hrh', 'Howrah'),
        ('hub-dhd', 'Hubballi-Dharwad'),
        ('hyd', 'Hyderabad'),
        ('icha', 'Ichalkaranji'),
        ('imp', 'Imphal'),
        ('indr', 'Indore'),
        ('jblpr', 'Jabalpur'),
        ('jpr', 'Jaipur'),
        ('jldr', 'Jalandhar'),
        ('jlgn', 'Jalgaon'),
        ('jln', 'Jalna'),
        ('jmu', 'Jammu'),
        ('jmngr', 'Jamnagar'),
        ('jmsdpr', 'Jamshedpur'),
        ('jhns', 'Jhansi'),
        ('jdhpr', 'Jodhpur'),
        ('jngd', 'Junagadh'),
        ('kdp', 'Kadapa'),
        ('kknd', 'Kakinada'),
        ('klyn-dom', 'Kalyan-Dombivali'),
        ('kmrht', 'Kamarhati'),
        ('kpr', 'Kanpur'),
        ('krwlngr', 'Karawal Nagar'),
        ('krmngr', 'Karimnagar'),
        ('krnl', 'Karnal'),
        ('kthr', 'Katihar'),
        ('khm', 'Khammam'),
        ('kirslm', 'Kirari Suleman Nagar'),
        ('koch', 'Kochi'),
        ('kolpr', 'Kolhapur'),
        ('kkt', 'Kolkata'),
        ('kolm', 'Kollam'),
        ('kor', 'Korba'),
        ('kta', 'Kota'),
        ('koz', 'Kozhikode'),
        ('kul', 'Kulti'),
        ('knl', 'Kurnool'),
        ('ltr', 'Latur'),
        ('le', 'Leh'),
        ('lonval', 'Lonavala'),
        ('lon', 'Lonavla'),
        ('ln', 'Loni'),
        ('luck', 'Lucknow'),
        ('ludh', 'Ludhiana'),
        ('mdri', 'Madurai'),
        ('mhshtl', 'Maheshtala'),
        ('malgn', 'Malegaon'),
        ('mnli', 'Manali'),
        ('mndr', 'Mandarmani'),
        ('mnglr', 'Mangalore'),
        ('mthr', 'Mathura'),
        ('mu', 'Mau'),
        ('mrt', 'Meerut'),
        ('mrza', 'Mirza-Bhayandar'),
        ('mrzpr', 'Mirzapur'),
        ('mrdbd', 'Moradabad'),
        ('mum', 'Mumbai'),
        ('muzafngr', 'Muzaffarnagar'),
        ('muzafpur', 'Muzaffarpur'),
        ('mysr', 'Mysore'),
        ('ngpr', 'Nagpur'),
        ('nand', 'Nanded'),
        ('nask', 'Nashik'),
        ('nv mum', 'Navi Mumbai'),
        ('nlr', 'Nellore'),
        ('nwdel', 'New Delhi'),
        ('nizmbd', 'Nizamabad'),
        ('nda', 'Noida'),
        ('nor dum', 'North Dumdum'),
        ('ozhu', 'Ozhukarai'),
        ('pli', 'Pali'),
        ('pnht', 'Panahati'),
        ('panpt', 'Panipat'),
        ('prbhn', 'Parbhani'),
        ('ptila', 'Patiala'),
        ('ptn', 'Patna'),
        ('pim-chin', 'Pimpri-Chinchwad'),
        ('pudchr', 'Puducherry'),
        ('pun', 'Pune'),
        ('purn', 'Purnia'),
        ('rchr', 'Raichur'),
        ('raigd', 'Raigad'),
        ('rpr', 'Raipur'),
        ('rjmdry', 'Rajamundry'),
        ('rjkt', 'Rajkot'),
        ('rjpr snrpr', 'Rajpur Sonarpur'),
        ('rmgdm', 'Ramagundam'),
        ('rmpr', 'Rampur'),
        ('rnch', 'Ranchi'),
        ('rtlm', 'Ratlam'),
        ('rwa', 'Rewa'),
        ('rtk', 'Rohtak'),
        ('rork', 'Rourkela'),
        ('sgr', 'Sagar'),
        ('shrnpr', 'Saharanpur'),
        ('slm', 'Salem'),
        ('san-mir', 'Sangli-Miraj & Kupwad'),
        ('stra', 'Satara'),
        ('stn', 'Satna'),
        ('shjnpr', 'Shahjahanpur'),
        ('shml', 'Shimla'),
        ('shmg', 'Shimoga'),
        ('shvmg', 'Shivamogga'),
        ('skr', 'Sikar'),
        ('slgri', 'Siliguri'),
        ('slpr', 'Solapur'),
        ('soudm', 'South Dumdum'),
        ('sri gng', 'Sri Ganganar'),
        ('srngr', 'Srinagar'),
        ('srt', 'surat'),
        ('than', 'Thane'),
        ('thrvntprm', 'Thiruvananthapuram'),
        ('thtkd', 'Thoothukudi'),
        ('thrsr', 'Thrissur'),
        ('truchpli', 'Tiruchirapalli'),
        ('tiruvel', 'Tirunelveli'),
        ('tpt', 'Tirupati'),
        ('tpr', 'Tiruppur'),
        ('tirvtur', 'Tiruvottiyur'),
        ('tkr', 'Tumkur'),
        ('udpr', 'Udaipur'),
        ('ujn', 'Ujjain'),
        ('ulsngr', 'Ulhasnagar'),
        ('vdor', 'Vadodara'),
        ('vrn', 'Varanasi'),
        ('vas-vr', 'Vasai-Virar'),
        ('vijngrm', 'Vijayanagaram'),
         ('vij', 'Vijayawada'),
         ('vizag', 'Visakhapatnam'),
         ('wrngl', 'Warangal'),
         ('zir', 'Ziro'),

         )
'''

HOW__CHOICES = (
        ('','How you know about Ercess Live *'),
        ('news','News'),
        ('engines','Search engines'),
        ('media','Socail media'),
        ('email','Email marketing'),
        ('word of mouth','Word of mouth'),
        ('others','Others'),
    )


