# Generated by Django 2.1.7 on 2019-12-20 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
#         migrations.AlterModelOptions(
#             name='users',
#             options={},
#         ),
#         migrations.AlterField(
#             model_name='expectationsfeedbacks',
#             name='exp_timestamp',
#             field=models.DateTimeField(default=datetime.datetime(2019, 12, 20, 12, 33, 43, 150008)),
#         ),
#         migrations.AlterField(
#             model_name='expectationsfeedbacks',
#             name='feedback_timestamp',
#             field=models.DateTimeField(default=datetime.datetime(2019, 12, 20, 12, 33, 43, 150056)),
#         ),
    ]
