# Generated by Django 2.1.7 on 2019-12-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_delete_expectationsfeedbacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectationsFeedbacks',
            fields=[
                ('expectations_feedbacks_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('booking_id', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=50)),
                ('expectation_msg', models.TextField(max_length=500, null=True)),
                ('uploaded_by', models.IntegerField(default=0)),
                ('exp_email_attempts', models.IntegerField(default=0)),
                ('exp_mail_status', models.CharField(default='pending', max_length=20)),
                ('exp_timestamp', models.DateTimeField(auto_now_add=True)),
                ('feedback_rating', models.IntegerField(default=0)),
                ('feedback_msg', models.TextField(max_length=500, null=True)),
                ('feedback_mail_attempts', models.IntegerField(default=0)),
                ('feedback_timestamp', models.DateTimeField(auto_now_add=True)),
                ('feedback_mail_status', models.CharField(default='pending', max_length=20)),
                ('provided_for', models.CharField(default='expectation_and_feedback', max_length=50)),
            ],
            options={
                'db_table': 'expectations_feedbacks',
            },
        ),
    ]
