# Generated by Django 2.1.7 on 2019-12-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_expectationsfeedbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuspromotionticketing',
            name='email_credit',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='statuspromotionticketing',
            name='referrer_program_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='statuspromotionticketing',
            name='sms_credit',
            field=models.IntegerField(default=1000),
        ),
    ]
