# Generated by Django 2.1.7 on 2019-12-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20191224_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectationsfeedbacks',
            name='email',
            field=models.EmailField(default='email not provide', max_length=50),
        ),
    ]
