# Generated by Django 2.1.7 on 2020-02-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20191226_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSalesReference',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_id', models.CharField(default='', max_length=20)),
                ('event_id', models.IntegerField(default=0)),
                ('used_referred_code', models.CharField(max_length=30)),
                ('cashback_to_process', models.IntegerField(default=0)),
                ('cashback_process_status', models.CharField(default='', max_length=30)),
            ],
            options={
                'db_table': 'ticket_sales_reference',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='expectationsfeedbacks',
            name='booking_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
