# Generated by Django 2.1.7 on 2020-03-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200220_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuspromotionticketing',
            name='affiliate',
            field=models.IntegerField(default=0),
        ),
    ]
