# Generated by Django 2.1.7 on 2020-04-14 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_statuspromotionticketing_affiliate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles2',
            options={'managed': True},
        ),
    ]
