# Generated by Django 2.1.7 on 2020-04-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200414_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles2',
            name='webinar_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='articles2',
            unique_together={('event_name', 'sdate', 'edate', 'full_address')},
        ),
    ]
