# Generated by Django 2.1.7 on 2020-04-14 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200414_0626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles2',
            options={'managed': False},
        ),
    ]
